# ==================== CALLING CODES TO COUNTRY (COMPLETE) ====================

CALLING_CODES = {
    # ==================== NORTH AMERICA (Country Code +1) ====================
    1: "United States",
    1: "Canada",
    1203: "United States (Connecticut)",
    1205: "United States (Alabama)",
    1206: "United States (Washington)",
    1207: "United States (Maine)",
    1208: "United States (Idaho)",
    1209: "United States (California)",
    1210: "United States (Texas)",
    1212: "United States (New York)",
    1213: "United States (California)",
    1214: "United States (Texas)",
    1215: "United States (Pennsylvania)",
    1216: "United States (Ohio)",
    1217: "United States (Illinois)",
    1218: "United States (Minnesota)",
    1219: "United States (Indiana)",
    1220: "United States (Ohio)",
    1224: "United States (Illinois)",
    1225: "United States (Louisiana)",
    1228: "United States (Mississippi)",
    1229: "United States (Georgia)",
    1231: "United States (Michigan)",
    1234: "United States (Ohio)",
    1236: "United States (British Columbia)",
    1239: "United States (Florida)",
    1240: "United States (Maryland)",
    1242: "Bahamas",
    1246: "Barbados",
    1248: "United States (Michigan)",
    1249: "United States (Ontario)",
    1250: "United States (British Columbia)",
    1251: "United States (Alabama)",
    1252: "United States (North Carolina)",
    1253: "United States (Washington)",
    1254: "United States (Texas)",
    1256: "United States (Alabama)",
    1260: "United States (Indiana)",
    1262: "United States (Wisconsin)",
    1264: "Anguilla",
    1267: "United States (Pennsylvania)",
    1268: "Antigua and Barbuda",
    1269: "United States (Michigan)",
    1270: "United States (Kentucky)",
    1272: "United States (Pennsylvania)",
    1274: "United States (Wisconsin)",
    1276: "United States (Virginia)",
    1278: "United States (Virginia)",
    1280: "United States (Arizona)",
    1281: "United States (Texas)",
    1283: "United States (Ohio)",
    1284: "British Virgin Islands",
    1289: "United States (Ontario)",
    1301: "United States (Maryland)",
    1302: "United States (Delaware)",
    1303: "United States (Colorado)",
    1304: "United States (West Virginia)",
    1305: "United States (Florida)",
    1306: "Canada (Saskatchewan)",
    1307: "United States (Wyoming)",
    1308: "United States (Nebraska)",
    1309: "United States (Illinois)",
    1310: "United States (California)",
    1312: "United States (Illinois)",
    1313: "United States (Michigan)",
    1314: "United States (Missouri)",
    1315: "United States (New York)",
    1316: "United States (Kansas)",
    1317: "United States (Indiana)",
    1318: "United States (Louisiana)",
    1319: "United States (Iowa)",
    1320: "United States (Minnesota)",
    1321: "United States (Florida)",
    1323: "United States (California)",
    1325: "United States (Texas)",
    1326: "United States (Ohio)",
    1327: "United States (Ohio)",
    1328: "United States (North Carolina)",
    1330: "United States (Ohio)",
    1331: "United States (Illinois)",
    1332: "United States (New York)",
    1334: "United States (Alabama)",
    1336: "United States (North Carolina)",
    1337: "United States (Louisiana)",
    1339: "United States (Massachusetts)",
    1340: "US Virgin Islands",
    1341: "United States (California)",
    1343: "United States (Ontario)",
    1345: "Cayman Islands",
    1346: "United States (Texas)",
    1347: "United States (New York)",
    1350: "United States (California)",
    1351: "United States (Massachusetts)",
    1352: "United States (Florida)",
    1353: "United States (Indiana)",
    1354: "United States (Texas)",
    1355: "United States (Hawaii)",
    1360: "United States (Washington)",
    1361: "United States (Texas)",
    1364: "United States (Kentucky)",
    1365: "United States (Ontario)",
    1367: "United States (Montreal)",
    1369: "United States (California)",
    1380: "United States (Ohio)",
    1385: "United States (Utah)",
    1386: "United States (Florida)",
    1401: "United States (Rhode Island)",
    1402: "United States (Nebraska)",
    1403: "United States (Alberta)",
    1404: "United States (Georgia)",
    1405: "United States (Oklahoma)",
    1406: "United States (Montana)",
    1407: "United States (Florida)",
    1408: "United States (California)",
    1409: "United States (Texas)",
    1410: "United States (Maryland)",
    1412: "United States (Pennsylvania)",
    1413: "United States (Massachusetts)",
    1414: "United States (Wisconsin)",
    1415: "United States (California)",
    1416: "United States (Ontario)",
    1417: "United States (Missouri)",
    1418: "Canada (Quebec)",
    1419: "United States (Ohio)",
    1423: "United States (Tennessee)",
    1424: "United States (California)",
    1425: "United States (Washington)",
    1430: "United States (Texas)",
    1431: "United States (Manitoba)",
    1432: "United States (Texas)",
    1434: "United States (Virginia)",
    1435: "United States (Utah)",
    1436: "United States (Ohio)",
    1437: "Canada (Ontario)",
    1438: "United States (Quebec)",
    1440: "United States (Ohio)",
    1441: "Bermuda",
    1442: "United States (Maryland)",
    1443: "United States (Maryland)",
    1445: "United States (Pennsylvania)",
    1450: "Canada (British Columbia)",
    1458: "United States (Oregon)",
    1463: "United States (Indiana)",
    1464: "United States (New York)",
    1469: "United States (Texas)",
    1470: "United States (Georgia)",
    1473: "Grenada",
    1475: "United States (Connecticut)",
    1478: "United States (Georgia)",
    1479: "United States (Arkansas)",
    1480: "United States (Arizona)",
    1484: "United States (Pennsylvania)",
    1500: "United States (Oregon)",
    1501: "United States (Arkansas)",
    1502: "United States (Kentucky)",
    1503: "United States (Oregon)",
    1504: "United States (Louisiana)",
    1505: "United States (New Mexico)",
    1506: "Canada (New Brunswick)",
    1507: "United States (Minnesota)",
    1508: "United States (Massachusetts)",
    1509: "United States (Washington)",
    1510: "United States (California)",
    1512: "United States (Texas)",
    1513: "United States (Ohio)",
    1514: "Canada (Quebec)",
    1515: "United States (Iowa)",
    1516: "United States (New York)",
    1517: "United States (Michigan)",
    1518: "United States (New York)",
    1519: "United States (Ontario)",
    1520: "United States (Arizona)",
    1530: "United States (California)",
    1531: "United States (Nebraska)",
    1534: "United States (Wisconsin)",
    1539: "United States (Oklahoma)",
    1540: "United States (Virginia)",
    1541: "United States (Oregon)",
    1551: "United States (New Jersey)",
    1559: "United States (California)",
    1562: "United States (California)",
    1563: "United States (Iowa)",
    1564: "United States (Washington)",
    1566: "United States (Wyoming)",
    1567: "United States (Ohio)",
    1570: "United States (Pennsylvania)",
    1571: "United States (Virginia)",
    1573: "United States (Missouri)",
    1574: "United States (Indiana)",
    1575: "United States (New Mexico)",
    1579: "United States (Quebec)",
    1580: "United States (Oklahoma)",
    1581: "Canada (Quebec)",
    1585: "United States (New York)",
    1586: "United States (Michigan)",
    1587: "Canada (Alberta)",
    1600: "United States (Idaho)",
    1601: "United States (Mississippi)",
    1602: "United States (Arizona)",
    1603: "United States (New Hampshire)",
    1604: "Canada (British Columbia)",
    1605: "United States (South Dakota)",
    1606: "United States (Kentucky)",
    1607: "United States (New York)",
    1608: "United States (Wisconsin)",
    1609: "United States (New Jersey)",
    1610: "United States (Pennsylvania)",
    1612: "United States (Minnesota)",
    1613: "United States (Ontario)",
    1614: "United States (Ohio)",
    1615: "United States (Tennessee)",
    1616: "United States (Michigan)",
    1617: "United States (Massachusetts)",
    1618: "United States (Illinois)",
    1619: "United States (California)",
    1620: "United States (Kansas)",
    1623: "United States (Arizona)",
    1626: "United States (California)",
    1628: "United States (California)",
    1629: "United States (Tennessee)",
    1630: "United States (Illinois)",
    1631: "United States (New York)",
    1636: "United States (Missouri)",
    1639: "Canada (Saskatchewan)",
    1640: "United States (New Jersey)",
    1641: "United States (Iowa)",
    1646: "United States (New York)",
    1647: "Canada (Ontario)",
    1649: "Turks and Caicos Islands",
    1650: "United States (California)",
    1651: "United States (Minnesota)",
    1657: "United States (California)",
    1658: "United States (Jamaica)",
    1659: "United States (Alabama)",
    1660: "United States (Missouri)",
    1661: "United States (California)",
    1662: "United States (Mississippi)",
    1663: "United States (Minnesota)",
    1664: "Montserrat",
    1667: "United States (Maryland)",
    1668: "United States (North Carolina)",
    1669: "United States (California)",
    1670: "Northern Mariana Islands",
    1671: "Guam",
    1672: "Canada (British Columbia)",
    1678: "United States (Georgia)",
    1680: "United States (New York)",
    1681: "United States (West Virginia)",
    1682: "United States (Texas)",
    1684: "American Samoa",
    1700: "United States (Montana)",
    1701: "United States (North Dakota)",
    1702: "United States (Nevada)",
    1703: "United States (Virginia)",
    1704: "United States (North Carolina)",
    1705: "Canada (Ontario)",
    1706: "United States (Georgia)",
    1707: "United States (California)",
    1708: "United States (Illinois)",
    1709: "Canada (Newfoundland)",
    1710: "United States (New York)",
    1712: "United States (Iowa)",
    1713: "United States (Texas)",
    1714: "United States (California)",
    1715: "United States (Wisconsin)",
    1716: "United States (New York)",
    1717: "United States (Pennsylvania)",
    1718: "United States (New York)",
    1719: "United States (Colorado)",
    1720: "United States (Colorado)",
    1721: "Sint Maarten",
    1724: "United States (Pennsylvania)",
    1725: "United States (Nevada)",
    1726: "United States (Texas)",
    1727: "United States (Florida)",
    1731: "United States (Tennessee)",
    1732: "United States (New Jersey)",
    1734: "United States (Michigan)",
    1737: "United States (Texas)",
    1740: "United States (Ohio)",
    1743: "United States (North Carolina)",
    1747: "United States (California)",
    1752: "United States (Virginia)",
    1754: "United States (Florida)",
    1757: "United States (Virginia)",
    1758: "Saint Lucia",
    1760: "United States (California)",
    1762: "United States (Georgia)",
    1763: "United States (Minnesota)",
    1765: "United States (Indiana)",
    1767: "Dominica",
    1769: "United States (Mississippi)",
    1770: "United States (Georgia)",
    1772: "United States (Florida)",
    1773: "United States (Illinois)",
    1774: "United States (Massachusetts)",
    1775: "United States (Nevada)",
    1778: "Canada (British Columbia)",
    1779: "United States (New York)",
    1780: "Canada (Alberta)",
    1781: "United States (Massachusetts)",
    1782: "Canada (Nova Scotia)",
    1784: "Saint Vincent and the Grenadines",
    1785: "United States (Kansas)",
    1786: "United States (Florida)",
    1787: "Puerto Rico",
    1801: "United States (Utah)",
    1802: "United States (Vermont)",
    1803: "United States (South Carolina)",
    1804: "United States (Virginia)",
    1805: "United States (California)",
    1806: "United States (Texas)",
    1807: "Canada (Ontario)",
    1808: "United States (Hawaii)",
    1809: "Dominican Republic",
    1810: "United States (Michigan)",
    1812: "United States (Indiana)",
    1813: "United States (Florida)",
    1814: "United States (Pennsylvania)",
    1815: "United States (Illinois)",
    1816: "United States (Missouri)",
    1817: "United States (Texas)",
    1818: "United States (California)",
    1819: "Canada (Quebec)",
    1820: "United States (Kansas)",
    1825: "Canada (Alberta)",
    1828: "United States (North Carolina)",
    1829: "Dominican Republic",
    1830: "United States (Texas)",
    1831: "United States (California)",
    1832: "United States (Texas)",
    1835: "United States (Pennsylvania)",
    1838: "United States (New York)",
    1839: "United States (Pennsylvania)",
    1840: "United States (Ontario)",
    1843: "United States (South Carolina)",
    1844: "Canada (Toll Free)",
    1845: "United States (New York)",
    1847: "United States (Illinois)",
    1848: "United States (New Jersey)",
    1849: "Dominican Republic",
    1850: "United States (Florida)",
    1854: "United States (South Carolina)",
    1856: "United States (New Jersey)",
    1857: "United States (Massachusetts)",
    1858: "United States (California)",
    1859: "United States (Kentucky)",
    1860: "United States (Connecticut)",
    1862: "United States (New Jersey)",
    1863: "United States (Florida)",
    1864: "United States (South Carolina)",
    1865: "United States (Tennessee)",
    1867: "Canada (Northwest Territories)",
    1868: "Trinidad and Tobago",
    1869: "Saint Kitts and Nevis",
    1870: "United States (Arkansas)",
    1872: "United States (Georgia)",
    1873: "Canada (Quebec)",
    1875: "United States (Mississippi)",
    1876: "Jamaica",
    1878: "United States (Pennsylvania)",
    1879: "United States (New Hampshire)",
    1901: "United States (Tennessee)",
    1902: "Canada (Nova Scotia)",
    1903: "United States (Texas)",
    1904: "United States (Florida)",
    1905: "Canada (Ontario)",
    1906: "United States (Michigan)",
    1907: "United States (Alaska)",
    1908: "United States (New Jersey)",
    1909: "United States (California)",
    1910: "United States (North Carolina)",
    1912: "United States (Georgia)",
    1913: "United States (Kansas)",
    1914: "United States (New York)",
    1915: "United States (Texas)",
    1916: "United States (California)",
    1917: "United States (New York)",
    1918: "United States (Oklahoma)",
    1919: "United States (North Carolina)",
    1920: "United States (Wisconsin)",
    1925: "United States (California)",
    1928: "United States (Arizona)",
    1929: "United States (New York)",
    1930: "United States (Indiana)",
    1931: "United States (Tennessee)",
    1935: "United States (Massachusetts)",
    1936: "United States (Texas)",
    1937: "United States (Ohio)",
    1938: "United States (Alabama)",
    1939: "United States (Massachusetts)",
    1940: "United States (Texas)",
    1941: "United States (Florida)",
    1943: "United States (Georgia)",
    1947: "United States (New York)",
    1948: "United States (Florida)",
    1949: "United States (California)",
    1951: "United States (California)",
    1952: "United States (Minnesota)",
    1953: "United States (Washington)",
    1954: "United States (Florida)",
    1956: "United States (Texas)",
    1957: "United States (Virginia)",
    1958: "United States (Florida)",
    1959: "United States (Connecticut)",
    1970: "United States (Colorado)",
    1971: "United States (California)",
    1972: "United States (Texas)",
    1973: "United States (New Jersey)",
    1974: "United States (Pennsylvania)",
    1975: "United States (Massachusetts)",
    1978: "United States (Massachusetts)",
    1979: "United States (Michigan)",
    1980: "United States (North Carolina)",
    1984: "United States (North Carolina)",
    1985: "United States (Louisiana)",
    1986: "United States (Idaho)",
    1989: "United States (Michigan)",
    
    # ==================== CENTRAL AMERICA ====================
    501: "Belize",
    502: "Guatemala",
    503: "El Salvador",
    504: "Honduras",
    505: "Nicaragua",
    506: "Costa Rica",
    507: "Panama",
    
    # ==================== SOUTH AMERICA ====================
    54: "Argentina",
    55: "Brazil",
    56: "Chile",
    57: "Colombia",
    58: "Venezuela",
    591: "Bolivia",
    592: "Guyana",
    593: "Ecuador",
    594: "French Guiana",
    595: "Paraguay",
    596: "Martinique",
    597: "Suriname",
    598: "Uruguay",
    
    # ==================== EUROPE ====================
    7: "Russia",
    20: "Egypt",
    27: "South Africa",
    30: "Greece",
    31: "Netherlands",
    32: "Belgium",
    33: "France",
    34: "Spain",
    36: "Hungary",
    39: "Italy",
    40: "Romania",
    41: "Switzerland",
    43: "Austria",
    44: "United Kingdom",
    45: "Denmark",
    46: "Sweden",
    47: "Norway",
    48: "Poland",
    49: "Germany",
    211: "South Sudan",
    212: "Morocco",
    213: "Algeria",
    216: "Tunisia",
    218: "Libya",
    220: "Gambia",
    221: "Senegal",
    222: "Mauritania",
    223: "Mali",
    224: "Guinea",
    225: "Ivory Coast",
    226: "Burkina Faso",
    227: "Niger",
    228: "Togo",
    229: "Benin",
    230: "Mauritius",
    231: "Liberia",
    232: "Sierra Leone",
    233: "Ghana",
    234: "Nigeria",
    235: "Chad",
    236: "Central African Republic",
    237: "Cameroon",
    238: "Cape Verde",
    239: "Sao Tome and Principe",
    240: "Equatorial Guinea",
    241: "Gabon",
    242: "Republic of the Congo",
    243: "Democratic Republic of the Congo",
    244: "Angola",
    245: "Guinea-Bissau",
    246: "Diego Garcia",
    247: "Ascension Island",
    248: "Seychelles",
    249: "Sudan",
    250: "Rwanda",
    251: "Ethiopia",
    252: "Somalia",
    253: "Djibouti",
    254: "Kenya",
    255: "Tanzania",
    256: "Uganda",
    257: "Burundi",
    258: "Mozambique",
    260: "Zambia",
    261: "Madagascar",
    262: "Reunion",
    263: "Zimbabwe",
    264: "Namibia",
    265: "Malawi",
    266: "Lesotho",
    267: "Botswana",
    268: "Eswatini",
    269: "Comoros",
    290: "Saint Helena",
    291: "Eritrea",
    297: "Aruba",
    298: "Faroe Islands",
    299: "Greenland",
    350: "Gibraltar",
    351: "Portugal",
    352: "Luxembourg",
    353: "Ireland",
    354: "Iceland",
    355: "Albania",
    356: "Malta",
    357: "Cyprus",
    358: "Finland",
    359: "Bulgaria",
    370: "Lithuania",
    371: "Latvia",
    372: "Estonia",
    373: "Moldova",
    374: "Armenia",
    375: "Belarus",
    376: "Andorra",
    377: "Monaco",
    378: "San Marino",
    379: "Vatican City",
    380: "Ukraine",
    381: "Serbia",
    382: "Montenegro",
    383: "Kosovo",
    385: "Croatia",
    386: "Slovenia",
    387: "Bosnia and Herzegovina",
    389: "North Macedonia",
    420: "Czech Republic",
    421: "Slovakia",
    423: "Liechtenstein",
    
    # ==================== ASIA ====================
    60: "Malaysia",
    62: "Indonesia",
    63: "Philippines",
    64: "New Zealand",
    65: "Singapore",
    66: "Thailand",
    81: "Japan",
    82: "South Korea",
    84: "Vietnam",
    86: "China",
    90: "Turkey",
    91: "India",
    92: "Pakistan",
    93: "Afghanistan",
    94: "Sri Lanka",
    95: "Myanmar",
    98: "Iran",
    960: "Maldives",
    961: "Lebanon",
    962: "Jordan",
    963: "Syria",
    964: "Iraq",
    965: "Kuwait",
    966: "Saudi Arabia",
    967: "Yemen",
    968: "Oman",
    970: "Palestine",
    971: "United Arab Emirates",
    972: "Israel",
    973: "Bahrain",
    974: "Qatar",
    975: "Bhutan",
    976: "Mongolia",
    977: "Nepal",
    992: "Tajikistan",
    993: "Turkmenistan",
    994: "Azerbaijan",
    995: "Georgia",
    996: "Kyrgyzstan",
    998: "Uzbekistan",
    
    # ==================== SOUTHEAST ASIA (continued) ====================
    670: "East Timor",
    672: "Australian External Territories",
    673: "Brunei",
    674: "Nauru",
    675: "Papua New Guinea",
    676: "Tonga",
    677: "Solomon Islands",
    678: "Vanuatu",
    679: "Fiji",
    680: "Palau",
    681: "Wallis and Futuna",
    682: "Cook Islands",
    683: "Niue",
    685: "Samoa",
    686: "Kiribati",
    687: "New Caledonia",
    688: "Tuvalu",
    689: "French Polynesia",
    690: "Tokelau",
    691: "Micronesia",
    692: "Marshall Islands",
    855: "Cambodia",
    856: "Laos",
    880: "Bangladesh",
    
    # ==================== OTHER / INTERNATIONAL ====================
    800: "International Freephone",
    808: "International Shared Cost",
    870: "Inmarsat",
    878: "Universal Personal Telecommunications",
    881: "Global Mobile Satellite System",
    882: "International Networks",
    883: "International Networks",
    979: "International Premium Rate",
}

# ==================== COMPLETE COUNTRY TO CALLING CODE ====================

COUNTRY_TO_CODE = {
    # Asia
    "Afghanistan": 93,
    "Armenia": 374,
    "Azerbaijan": 994,
    "Bahrain": 973,
    "Bangladesh": 880,
    "Bhutan": 975,
    "Brunei": 673,
    "Cambodia": 855,
    "China": 86,
    "Cyprus": 357,
    "Georgia": 995,
    "India": 91,
    "Indonesia": 62,
    "Iran": 98,
    "Iraq": 964,
    "Israel": 972,
    "Japan": 81,
    "Jordan": 962,
    "Kazakhstan": 7,
    "Kuwait": 965,
    "Kyrgyzstan": 996,
    "Laos": 856,
    "Lebanon": 961,
    "Malaysia": 60,
    "Maldives": 960,
    "Mongolia": 976,
    "Myanmar": 95,
    "Nepal": 977,
    "North Korea": 850,
    "Oman": 968,
    "Pakistan": 92,
    "Palestine": 970,
    "Philippines": 63,
    "Qatar": 974,
    "Russia": 7,
    "Saudi Arabia": 966,
    "Singapore": 65,
    "South Korea": 82,
    "Sri Lanka": 94,
    "Syria": 963,
    "Taiwan": 886,
    "Tajikistan": 992,
    "Thailand": 66,
    "East Timor": 670,
    "Turkey": 90,
    "Turkmenistan": 993,
    "United Arab Emirates": 971,
    "Uzbekistan": 998,
    "Vietnam": 84,
    "Yemen": 967,
    
    # Europe
    "Albania": 355,
    "Andorra": 376,
    "Austria": 43,
    "Belarus": 375,
    "Belgium": 32,
    "Bosnia and Herzegovina": 387,
    "Bulgaria": 359,
    "Croatia": 385,
    "Czech Republic": 420,
    "Denmark": 45,
    "Estonia": 372,
    "Finland": 358,
    "France": 33,
    "Germany": 49,
    "Greece": 30,
    "Hungary": 36,
    "Iceland": 354,
    "Ireland": 353,
    "Italy": 39,
    "Kosovo": 383,
    "Latvia": 371,
    "Liechtenstein": 423,
    "Lithuania": 370,
    "Luxembourg": 352,
    "Malta": 356,
    "Moldova": 373,
    "Monaco": 377,
    "Montenegro": 382,
    "Netherlands": 31,
    "North Macedonia": 389,
    "Norway": 47,
    "Poland": 48,
    "Portugal": 351,
    "Romania": 40,
    "San Marino": 378,
    "Serbia": 381,
    "Slovakia": 421,
    "Slovenia": 386,
    "Spain": 34,
    "Sweden": 46,
    "Switzerland": 41,
    "Ukraine": 380,
    "United Kingdom": 44,
    "Vatican City": 379,
    
    # North America
    "Antigua and Barbuda": 1268,
    "Bahamas": 1242,
    "Barbados": 1246,
    "Belize": 501,
    "Canada": 1,
    "Costa Rica": 506,
    "Cuba": 53,
    "Dominica": 1767,
    "Dominican Republic": 1809,
    "El Salvador": 503,
    "Grenada": 1473,
    "Guatemala": 502,
    "Haiti": 509,
    "Honduras": 504,
    "Jamaica": 1876,
    "Mexico": 52,
    "Nicaragua": 505,
    "Panama": 507,
    "Saint Kitts and Nevis": 1869,
    "Saint Lucia": 1758,
    "Saint Vincent and the Grenadines": 1784,
    "Trinidad and Tobago": 1868,
    "United States": 1,
    
    # South America
    "Argentina": 54,
    "Bolivia": 591,
    "Brazil": 55,
    "Chile": 56,
    "Colombia": 57,
    "Ecuador": 593,
    "Guyana": 592,
    "Paraguay": 595,
    "Peru": 51,
    "Suriname": 597,
    "Uruguay": 598,
    "Venezuela": 58,
    
    # Africa
    "Algeria": 213,
    "Angola": 244,
    "Benin": 229,
    "Botswana": 267,
    "Burkina Faso": 226,
    "Burundi": 257,
    "Cameroon": 237,
    "Cape Verde": 238,
    "Central African Republic": 236,
    "Chad": 235,
    "Comoros": 269,
    "Democratic Republic of the Congo": 243,
    "Republic of the Congo": 242,
    "Djibouti": 253,
    "Egypt": 20,
    "Equatorial Guinea": 240,
    "Eritrea": 291,
    "Eswatini": 268,
    "Ethiopia": 251,
    "Gabon": 241,
    "Gambia": 220,
    "Ghana": 233,
    "Guinea": 224,
    "Guinea-Bissau": 245,
    "Ivory Coast": 225,
    "Kenya": 254,
    "Lesotho": 266,
    "Liberia": 231,
    "Libya": 218,
    "Madagascar": 261,
    "Malawi": 265,
    "Mali": 223,
    "Mauritania": 222,
    "Mauritius": 230,
    "Morocco": 212,
    "Mozambique": 258,
    "Namibia": 264,
    "Niger": 227,
    "Nigeria": 234,
    "Rwanda": 250,
    "Sao Tome and Principe": 239,
    "Senegal": 221,
    "Seychelles": 248,
    "Sierra Leone": 232,
    "Somalia": 252,
    "South Africa": 27,
    "South Sudan": 211,
    "Sudan": 249,
    "Tanzania": 255,
    "Togo": 228,
    "Tunisia": 216,
    "Uganda": 256,
    "Zambia": 260,
    "Zimbabwe": 263,
    
    # Oceania
    "Australia": 61,
    "Fiji": 679,
    "Kiribati": 686,
    "Marshall Islands": 692,
    "Micronesia": 691,
    "Nauru": 674,
    "New Zealand": 64,
    "Palau": 680,
    "Papua New Guinea": 675,
    "Samoa": 685,
    "Solomon Islands": 677,
    "Tonga": 676,
    "Tuvalu": 688,
    "Vanuatu": 678,
    
    # Territories
    "American Samoa": 1684,
    "Anguilla": 1264,
    "Aruba": 297,
    "Bermuda": 1441,
    "British Virgin Islands": 1284,
    "Cayman Islands": 1345,
    "Cook Islands": 682,
    "Falkland Islands": 500,
    "Faroe Islands": 298,
    "French Guiana": 594,
    "French Polynesia": 689,
    "Gibraltar": 350,
    "Greenland": 299,
    "Guadeloupe": 590,
    "Guam": 1671,
    "Martinique": 596,
    "Montserrat": 1664,
    "New Caledonia": 687,
    "Niue": 683,
    "Northern Mariana Islands": 1670,
    "Puerto Rico": 1787,
    "Reunion": 262,
    "Saint Helena": 290,
    "Sint Maarten": 1721,
    "Turks and Caicos Islands": 1649,
    "US Virgin Islands": 1340,
    "Wallis and Futuna": 681,
}

# ==================== COMPLETE ISO CODES ====================

ISO_ALPHA2 = {
    # Asia
    "Afghanistan": "AF",
    "Armenia": "AM",
    "Azerbaijan": "AZ",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Bhutan": "BT",
    "Brunei": "BN",
    "Cambodia": "KH",
    "China": "CN",
    "Cyprus": "CY",
    "Georgia": "GE",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Israel": "IL",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Lebanon": "LB",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mongolia": "MN",
    "Myanmar": "MM",
    "Nepal": "NP",
    "North Korea": "KP",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palestine": "PS",
    "Philippines": "PH",
    "Qatar": "QA",
    "Russia": "RU",
    "Saudi Arabia": "SA",
    "Singapore": "SG",
    "South Korea": "KR",
    "Sri Lanka": "LK",
    "Syria": "SY",
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Thailand": "TH",
    "East Timor": "TL",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "United Arab Emirates": "AE",
    "Uzbekistan": "UZ",
    "Vietnam": "VN",
    "Yemen": "YE",
    
    # Europe
    "Albania": "AL",
    "Andorra": "AD",
    "Austria": "AT",
    "Belarus": "BY",
    "Belgium": "BE",
    "Bosnia and Herzegovina": "BA",
    "Bulgaria": "BG",
    "Croatia": "HR",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Estonia": "EE",
    "Finland": "FI",
    "France": "FR",
    "Germany": "DE",
    "Greece": "GR",
    "Hungary": "HU",
    "Iceland": "IS",
    "Ireland": "IE",
    "Italy": "IT",
    "Kosovo": "XK",
    "Latvia": "LV",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Malta": "MT",
    "Moldova": "MD",
    "Monaco": "MC",
    "Montenegro": "ME",
    "Netherlands": "NL",
    "North Macedonia": "MK",
    "Norway": "NO",
    "Poland": "PL",
    "Portugal": "PT",
    "Romania": "RO",
    "San Marino": "SM",
    "Serbia": "RS",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Spain": "ES",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Ukraine": "UA",
    "United Kingdom": "GB",
    "Vatican City": "VA",
    
    # North America
    "Antigua and Barbuda": "AG",
    "Bahamas": "BS",
    "Barbados": "BB",
    "Belize": "BZ",
    "Canada": "CA",
    "Costa Rica": "CR",
    "Cuba": "CU",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "El Salvador": "SV",
    "Grenada": "GD",
    "Guatemala": "GT",
    "Haiti": "HT",
    "Honduras": "HN",
    "Jamaica": "JM",
    "Mexico": "MX",
    "Nicaragua": "NI",
    "Panama": "PA",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Vincent and the Grenadines": "VC",
    "Trinidad and Tobago": "TT",
    "United States": "US",
    
    # South America
    "Argentina": "AR",
    "Bolivia": "BO",
    "Brazil": "BR",
    "Chile": "CL",
    "Colombia": "CO",
    "Ecuador": "EC",
    "Guyana": "GY",
    "Paraguay": "PY",
    "Peru": "PE",
    "Suriname": "SR",
    "Uruguay": "UY",
    "Venezuela": "VE",
    
    # Africa
    "Algeria": "DZ",
    "Angola": "AO",
    "Benin": "BJ",
    "Botswana": "BW",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cameroon": "CM",
    "Cape Verde": "CV",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Comoros": "KM",
    "Democratic Republic of the Congo": "CD",
    "Republic of the Congo": "CG",
    "Djibouti": "DJ",
    "Egypt": "EG",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Eswatini": "SZ",
    "Ethiopia": "ET",
    "Gabon": "GA",
    "Gambia": "GM",
    "Ghana": "GH",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Ivory Coast": "CI",
    "Kenya": "KE",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Mali": "ML",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Namibia": "NA",
    "Niger": "NE",
    "Nigeria": "NG",
    "Rwanda": "RW",
    "Sao Tome and Principe": "ST",
    "Senegal": "SN",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Sudan": "SS",
    "Sudan": "SD",
    "Tanzania": "TZ",
    "Togo": "TG",
    "Tunisia": "TN",
    "Uganda": "UG",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
    
    # Oceania
    "Australia": "AU",
    "Fiji": "FJ",
    "Kiribati": "KI",
    "Marshall Islands": "MH",
    "Micronesia": "FM",
    "Nauru": "NR",
    "New Zealand": "NZ",
    "Palau": "PW",
    "Papua New Guinea": "PG",
    "Samoa": "WS",
    "Solomon Islands": "SB",
    "Tonga": "TO",
    "Tuvalu": "TV",
    "Vanuatu": "VU",
    
    # Territories
    "American Samoa": "AS",
    "Anguilla": "AI",
    "Aruba": "AW",
    "Bermuda": "BM",
    "British Virgin Islands": "VG",
    "Cayman Islands": "KY",
    "Cook Islands": "CK",
    "Falkland Islands": "FK",
    "Faroe Islands": "FO",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "Gibraltar": "GI",
    "Greenland": "GL",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Martinique": "MQ",
    "Montserrat": "MS",
    "New Caledonia": "NC",
    "Niue": "NU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "Reunion": "RE",
    "Saint Helena": "SH",
    "Sint Maarten": "SX",
    "Turks and Caicos Islands": "TC",
    "US Virgin Islands": "VI",
    "Wallis and Futuna": "WF",
}

# ==================== CONTINENTS (COMPLETE) ====================

COUNTRY_CONTINENT = {
    # ==================== ASIA (49 countries) ====================
    "Afghanistan": "Asia",
    "Armenia": "Asia",
    "Azerbaijan": "Asia",
    "Bahrain": "Asia",
    "Bangladesh": "Asia",
    "Bhutan": "Asia",
    "Brunei": "Asia",
    "Cambodia": "Asia",
    "China": "Asia",
    "Cyprus": "Asia",
    "Georgia": "Asia",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iran": "Asia",
    "Iraq": "Asia",
    "Israel": "Asia",
    "Japan": "Asia",
    "Jordan": "Asia",
    "Kazakhstan": "Asia",
    "Kuwait": "Asia",
    "Kyrgyzstan": "Asia",
    "Laos": "Asia",
    "Lebanon": "Asia",
    "Malaysia": "Asia",
    "Maldives": "Asia",
    "Mongolia": "Asia",
    "Myanmar": "Asia",
    "Nepal": "Asia",
    "North Korea": "Asia",
    "Oman": "Asia",
    "Pakistan": "Asia",
    "Palestine": "Asia",
    "Philippines": "Asia",
    "Qatar": "Asia",
    "Russia": "Asia",
    "Saudi Arabia": "Asia",
    "Singapore": "Asia",
    "South Korea": "Asia",
    "Sri Lanka": "Asia",
    "Syria": "Asia",
    "Taiwan": "Asia",
    "Tajikistan": "Asia",
    "Thailand": "Asia",
    "East Timor": "Asia",
    "Turkey": "Asia",
    "Turkmenistan": "Asia",
    "United Arab Emirates": "Asia",
    "Uzbekistan": "Asia",
    "Vietnam": "Asia",
    "Yemen": "Asia",
    
    # ==================== EUROPE (44 countries) ====================
    "Albania": "Europe",
    "Andorra": "Europe",
    "Austria": "Europe",
    "Belarus": "Europe",
    "Belgium": "Europe",
    "Bosnia and Herzegovina": "Europe",
    "Bulgaria": "Europe",
    "Croatia": "Europe",
    "Czech Republic": "Europe",
    "Denmark": "Europe",
    "Estonia": "Europe",
    "Finland": "Europe",
    "France": "Europe",
    "Germany": "Europe",
    "Greece": "Europe",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "Ireland": "Europe",
    "Italy": "Europe",
    "Kosovo": "Europe",
    "Latvia": "Europe",
    "Liechtenstein": "Europe",
    "Lithuania": "Europe",
    "Luxembourg": "Europe",
    "Malta": "Europe",
    "Moldova": "Europe",
    "Monaco": "Europe",
    "Montenegro": "Europe",
    "Netherlands": "Europe",
    "North Macedonia": "Europe",
    "Norway": "Europe",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Romania": "Europe",
    "San Marino": "Europe",
    "Serbia": "Europe",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Spain": "Europe",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Ukraine": "Europe",
    "United Kingdom": "Europe",
    "Vatican City": "Europe",
    
    # ==================== NORTH AMERICA (23 countries) ====================
    "Antigua and Barbuda": "North America",
    "Bahamas": "North America",
    "Barbados": "North America",
    "Belize": "North America",
    "Canada": "North America",
    "Costa Rica": "North America",
    "Cuba": "North America",
    "Dominica": "North America",
    "Dominican Republic": "North America",
    "El Salvador": "North America",
    "Grenada": "North America",
    "Guatemala": "North America",
    "Haiti": "North America",
    "Honduras": "North America",
    "Jamaica": "North America",
    "Mexico": "North America",
    "Nicaragua": "North America",
    "Panama": "North America",
    "Saint Kitts and Nevis": "North America",
    "Saint Lucia": "North America",
    "Saint Vincent and the Grenadines": "North America",
    "Trinidad and Tobago": "North America",
    "United States": "North America",
    
    # ==================== SOUTH AMERICA (12 countries) ====================
    "Argentina": "South America",
    "Bolivia": "South America",
    "Brazil": "South America",
    "Chile": "South America",
    "Colombia": "South America",
    "Ecuador": "South America",
    "Guyana": "South America",
    "Paraguay": "South America",
    "Peru": "South America",
    "Suriname": "South America",
    "Uruguay": "South America",
    "Venezuela": "South America",
    
    # ==================== AFRICA (54 countries) ====================
    "Algeria": "Africa",
    "Angola": "Africa",
    "Benin": "Africa",
    "Botswana": "Africa",
    "Burkina Faso": "Africa",
    "Burundi": "Africa",
    "Cameroon": "Africa",
    "Cape Verde": "Africa",
    "Central African Republic": "Africa",
    "Chad": "Africa",
    "Comoros": "Africa",
    "Democratic Republic of the Congo": "Africa",
    "Republic of the Congo": "Africa",
    "Djibouti": "Africa",
    "Egypt": "Africa",
    "Equatorial Guinea": "Africa",
    "Eritrea": "Africa",
    "Eswatini": "Africa",
    "Ethiopia": "Africa",
    "Gabon": "Africa",
    "Gambia": "Africa",
    "Ghana": "Africa",
    "Guinea": "Africa",
    "Guinea-Bissau": "Africa",
    "Ivory Coast": "Africa",
    "Kenya": "Africa",
    "Lesotho": "Africa",
    "Liberia": "Africa",
    "Libya": "Africa",
    "Madagascar": "Africa",
    "Malawi": "Africa",
    "Mali": "Africa",
    "Mauritania": "Africa",
    "Mauritius": "Africa",
    "Morocco": "Africa",
    "Mozambique": "Africa",
    "Namibia": "Africa",
    "Niger": "Africa",
    "Nigeria": "Africa",
    "Rwanda": "Africa",
    "Sao Tome and Principe": "Africa",
    "Senegal": "Africa",
    "Seychelles": "Africa",
    "Sierra Leone": "Africa",
    "Somalia": "Africa",
    "South Africa": "Africa",
    "South Sudan": "Africa",
    "Sudan": "Africa",
    "Tanzania": "Africa",
    "Togo": "Africa",
    "Tunisia": "Africa",
    "Uganda": "Africa",
    "Zambia": "Africa",
    "Zimbabwe": "Africa",
    
    # ==================== OCEANIA (14 countries) ====================
    "Australia": "Oceania",
    "Fiji": "Oceania",
    "Kiribati": "Oceania",
    "Marshall Islands": "Oceania",
    "Micronesia": "Oceania",
    "Nauru": "Oceania",
    "New Zealand": "Oceania",
    "Palau": "Oceania",
    "Papua New Guinea": "Oceania",
    "Samoa": "Oceania",
    "Solomon Islands": "Oceania",
    "Tonga": "Oceania",
    "Tuvalu": "Oceania",
    "Vanuatu": "Oceania",
    
    # ==================== TERRITORIES (by continent) ====================
    "American Samoa": "Oceania",
    "Anguilla": "North America",
    "Aruba": "North America",
    "Bermuda": "North America",
    "British Virgin Islands": "North America",
    "Cayman Islands": "North America",
    "Cook Islands": "Oceania",
    "Falkland Islands": "South America",
    "Faroe Islands": "Europe",
    "French Guiana": "South America",
    "French Polynesia": "Oceania",
    "Gibraltar": "Europe",
    "Greenland": "North America",
    "Guadeloupe": "North America",
    "Guam": "Oceania",
    "Martinique": "North America",
    "Montserrat": "North America",
    "New Caledonia": "Oceania",
    "Niue": "Oceania",
    "Northern Mariana Islands": "Oceania",
    "Puerto Rico": "North America",
    "Reunion": "Africa",
    "Saint Helena": "Africa",
    "Sint Maarten": "North America",
    "Turks and Caicos Islands": "North America",
    "US Virgin Islands": "North America",
    "Wallis and Futuna": "Oceania",
}

# ==================== OFFICIAL LANGUAGES (COMPLETE) ====================

COUNTRY_LANGUAGE = {
    # ==================== ASIA ====================
    "Afghanistan": ["Dari", "Pashto"],
    "Armenia": ["Armenian"],
    "Azerbaijan": ["Azerbaijani"],
    "Bahrain": ["Arabic"],
    "Bangladesh": ["Bengali"],
    "Bhutan": ["Dzongkha"],
    "Brunei": ["Malay"],
    "Cambodia": ["Khmer"],
    "China": ["Chinese", "Mandarin"],
    "Cyprus": ["Greek", "Turkish"],
    "Georgia": ["Georgian"],
    "India": ["Hindi", "English", "Bengali", "Telugu", "Marathi", "Tamil", "Urdu", 
               "Gujarati", "Malayalam", "Kannada", "Oriya", "Punjabi", "Assamese", 
               "Maithili", "Sanskrit", "Sindhi", "Nepali", "Konkani", "Bodo", "Dogri", 
               "Kashmiri", "Manipuri", "Santali"],
    "Indonesia": ["Indonesian"],
    "Iran": ["Persian"],
    "Iraq": ["Arabic", "Kurdish"],
    "Israel": ["Hebrew", "Arabic"],
    "Japan": ["Japanese"],
    "Jordan": ["Arabic"],
    "Kazakhstan": ["Kazakh", "Russian"],
    "Kuwait": ["Arabic"],
    "Kyrgyzstan": ["Kyrgyz", "Russian"],
    "Laos": ["Lao"],
    "Lebanon": ["Arabic", "French"],
    "Malaysia": ["Malay"],
    "Maldives": ["Dhivehi"],
    "Mongolia": ["Mongolian"],
    "Myanmar": ["Burmese"],
    "Nepal": ["Nepali"],
    "North Korea": ["Korean"],
    "Oman": ["Arabic"],
    "Pakistan": ["Urdu", "English"],
    "Palestine": ["Arabic"],
    "Philippines": ["Filipino", "English"],
    "Qatar": ["Arabic"],
    "Russia": ["Russian"],
    "Saudi Arabia": ["Arabic"],
    "Singapore": ["English", "Chinese", "Malay", "Tamil"],
    "South Korea": ["Korean"],
    "Sri Lanka": ["Sinhala", "Tamil"],
    "Syria": ["Arabic"],
    "Taiwan": ["Chinese", "Mandarin"],
    "Tajikistan": ["Tajik"],
    "Thailand": ["Thai"],
    "East Timor": ["Portuguese", "Tetum"],
    "Turkey": ["Turkish"],
    "Turkmenistan": ["Turkmen"],
    "United Arab Emirates": ["Arabic"],
    "Uzbekistan": ["Uzbek"],
    "Vietnam": ["Vietnamese"],
    "Yemen": ["Arabic"],
    
    # ==================== EUROPE ====================
    "Albania": ["Albanian"],
    "Andorra": ["Catalan"],
    "Austria": ["German"],
    "Belarus": ["Belarusian", "Russian"],
    "Belgium": ["Dutch", "French", "German"],
    "Bosnia and Herzegovina": ["Bosnian", "Croatian", "Serbian"],
    "Bulgaria": ["Bulgarian"],
    "Croatia": ["Croatian"],
    "Czech Republic": ["Czech"],
    "Denmark": ["Danish"],
    "Estonia": ["Estonian"],
    "Finland": ["Finnish", "Swedish"],
    "France": ["French"],
    "Germany": ["German"],
    "Greece": ["Greek"],
    "Hungary": ["Hungarian"],
    "Iceland": ["Icelandic"],
    "Ireland": ["Irish", "English"],
    "Italy": ["Italian"],
    "Kosovo": ["Albanian", "Serbian"],
    "Latvia": ["Latvian"],
    "Liechtenstein": ["German"],
    "Lithuania": ["Lithuanian"],
    "Luxembourg": ["Luxembourgish", "French", "German"],
    "Malta": ["Maltese", "English"],
    "Moldova": ["Romanian"],
    "Monaco": ["French"],
    "Montenegro": ["Montenegrin"],
    "Netherlands": ["Dutch"],
    "North Macedonia": ["Macedonian"],
    "Norway": ["Norwegian", "Bokmål", "Nynorsk"],
    "Poland": ["Polish"],
    "Portugal": ["Portuguese"],
    "Romania": ["Romanian"],
    "San Marino": ["Italian"],
    "Serbia": ["Serbian"],
    "Slovakia": ["Slovak"],
    "Slovenia": ["Slovenian"],
    "Spain": ["Spanish"],
    "Sweden": ["Swedish"],
    "Switzerland": ["German", "French", "Italian", "Romansh"],
    "Ukraine": ["Ukrainian"],
    "United Kingdom": ["English"],
    "Vatican City": ["Latin", "Italian"],
    
    # ==================== NORTH AMERICA ====================
    "Antigua and Barbuda": ["English"],
    "Bahamas": ["English"],
    "Barbados": ["English"],
    "Belize": ["English"],
    "Canada": ["English", "French"],
    "Costa Rica": ["Spanish"],
    "Cuba": ["Spanish"],
    "Dominica": ["English"],
    "Dominican Republic": ["Spanish"],
    "El Salvador": ["Spanish"],
    "Grenada": ["English"],
    "Guatemala": ["Spanish"],
    "Haiti": ["French", "Haitian Creole"],
    "Honduras": ["Spanish"],
    "Jamaica": ["English"],
    "Mexico": ["Spanish"],
    "Nicaragua": ["Spanish"],
    "Panama": ["Spanish"],
    "Saint Kitts and Nevis": ["English"],
    "Saint Lucia": ["English"],
    "Saint Vincent and the Grenadines": ["English"],
    "Trinidad and Tobago": ["English"],
    "United States": ["English"],
    
    # ==================== SOUTH AMERICA ====================
    "Argentina": ["Spanish"],
    "Bolivia": ["Spanish", "Quechua", "Aymara", "Guarani"],
    "Brazil": ["Portuguese"],
    "Chile": ["Spanish"],
    "Colombia": ["Spanish"],
    "Ecuador": ["Spanish"],
    "Guyana": ["English"],
    "Paraguay": ["Spanish", "Guarani"],
    "Peru": ["Spanish", "Quechua"],
    "Suriname": ["Dutch"],
    "Uruguay": ["Spanish"],
    "Venezuela": ["Spanish"],
    
    # ==================== AFRICA ====================
    "Algeria": ["Arabic", "Berber", "French"],
    "Angola": ["Portuguese"],
    "Benin": ["French"],
    "Botswana": ["English", "Setswana"],
    "Burkina Faso": ["French"],
    "Burundi": ["Kirundi", "French", "English"],
    "Cameroon": ["English", "French"],
    "Cape Verde": ["Portuguese", "Cape Verdean Creole"],
    "Central African Republic": ["Sango", "French"],
    "Chad": ["Arabic", "French"],
    "Comoros": ["Comorian", "Arabic", "French"],
    "Democratic Republic of the Congo": ["French"],
    "Republic of the Congo": ["French", "Lingala", "Kikongo"],
    "Djibouti": ["Arabic", "French"],
    "Egypt": ["Arabic"],
    "Equatorial Guinea": ["Spanish", "French", "Portuguese"],
    "Eritrea": ["Tigrinya", "Arabic", "English"],
    "Eswatini": ["Swazi", "English"],
    "Ethiopia": ["Amharic", "Oromo", "Somali", "Tigrinya"],
    "Gabon": ["French"],
    "Gambia": ["English"],
    "Ghana": ["English"],
    "Guinea": ["French"],
    "Guinea-Bissau": ["Portuguese", "Guinea-Bissau Creole"],
    "Ivory Coast": ["French"],
    "Kenya": ["Swahili", "English"],
    "Lesotho": ["Sesotho", "English"],
    "Liberia": ["English"],
    "Libya": ["Arabic"],
    "Madagascar": ["Malagasy", "French"],
    "Malawi": ["English", "Chichewa"],
    "Mali": ["French"],
    "Mauritania": ["Arabic", "French"],
    "Mauritius": ["English", "French", "Mauritian Creole"],
    "Morocco": ["Arabic", "Berber"],
    "Mozambique": ["Portuguese"],
    "Namibia": ["English"],
    "Niger": ["French"],
    "Nigeria": ["English"],
    "Rwanda": ["Kinyarwanda", "English", "French", "Swahili"],
    "Sao Tome and Principe": ["Portuguese"],
    "Senegal": ["French"],
    "Seychelles": ["Seychellois Creole", "English", "French"],
    "Sierra Leone": ["English"],
    "Somalia": ["Somali", "Arabic"],
    "South Africa": ["Afrikaans", "English", "Zulu", "Xhosa", "Venda", "Tswana", 
                     "Swati", "Ndebele", "Northern Sotho", "Southern Sotho", "Tsonga"],
    "South Sudan": ["English", "Arabic"],
    "Sudan": ["Arabic", "English"],
    "Tanzania": ["Swahili", "English"],
    "Togo": ["French"],
    "Tunisia": ["Arabic", "French"],
    "Uganda": ["English", "Swahili"],
    "Zambia": ["English"],
    "Zimbabwe": ["English", "Shona", "Ndebele"],
    
    # ==================== OCEANIA ====================
    "Australia": ["English"],
    "Fiji": ["English", "Fijian", "Hindi"],
    "Kiribati": ["English", "Gilbertese"],
    "Marshall Islands": ["Marshallese", "English"],
    "Micronesia": ["English"],
    "Nauru": ["Nauruan", "English"],
    "New Zealand": ["English", "Māori", "New Zealand Sign Language"],
    "Palau": ["Palauan", "English"],
    "Papua New Guinea": ["English", "Tok Pisin", "Hiri Motu"],
    "Samoa": ["Samoan", "English"],
    "Solomon Islands": ["English"],
    "Tonga": ["Tongan", "English"],
    "Tuvalu": ["Tuvaluan", "English"],
    "Vanuatu": ["Bislama", "English", "French"],
    
    # ==================== TERRITORIES ====================
    "American Samoa": ["English", "Samoan"],
    "Anguilla": ["English"],
    "Aruba": ["Dutch", "Papiamento"],
    "Bermuda": ["English"],
    "British Virgin Islands": ["English"],
    "Cayman Islands": ["English"],
    "Cook Islands": ["English", "Cook Islands Māori"],
    "Falkland Islands": ["English"],
    "Faroe Islands": ["Faroese", "Danish"],
    "French Guiana": ["French"],
    "French Polynesia": ["French", "Tahitian"],
    "Gibraltar": ["English"],
    "Greenland": ["Greenlandic", "Danish"],
    "Guadeloupe": ["French"],
    "Guam": ["English", "Chamorro"],
    "Martinique": ["French"],
    "Montserrat": ["English"],
    "New Caledonia": ["French"],
    "Niue": ["Niuean", "English"],
    "Northern Mariana Islands": ["English", "Chamorro", "Carolinian"],
    "Puerto Rico": ["Spanish", "English"],
    "Reunion": ["French"],
    "Saint Helena": ["English"],
    "Sint Maarten": ["Dutch", "English"],
    "Turks and Caicos Islands": ["English"],
    "US Virgin Islands": ["English"],
    "Wallis and Futuna": ["French", "Wallisian", "Futunan"],
}

# ==================== TOP-LEVEL DOMAINS (TLD - COMPLETE) ====================

COUNTRY_TLD = {
    # ==================== ASIA ====================
    "Afghanistan": ".af",
    "Armenia": ".am",
    "Azerbaijan": ".az",
    "Bahrain": ".bh",
    "Bangladesh": ".bd",
    "Bhutan": ".bt",
    "Brunei": ".bn",
    "Cambodia": ".kh",
    "China": ".cn",
    "Cyprus": ".cy",
    "Georgia": ".ge",
    "India": ".in",
    "Indonesia": ".id",
    "Iran": ".ir",
    "Iraq": ".iq",
    "Israel": ".il",
    "Japan": ".jp",
    "Jordan": ".jo",
    "Kazakhstan": ".kz",
    "Kuwait": ".kw",
    "Kyrgyzstan": ".kg",
    "Laos": ".la",
    "Lebanon": ".lb",
    "Malaysia": ".my",
    "Maldives": ".mv",
    "Mongolia": ".mn",
    "Myanmar": ".mm",
    "Nepal": ".np",
    "North Korea": ".kp",
    "Oman": ".om",
    "Pakistan": ".pk",
    "Palestine": ".ps",
    "Philippines": ".ph",
    "Qatar": ".qa",
    "Russia": ".ru",
    "Saudi Arabia": ".sa",
    "Singapore": ".sg",
    "South Korea": ".kr",
    "Sri Lanka": ".lk",
    "Syria": ".sy",
    "Taiwan": ".tw",
    "Tajikistan": ".tj",
    "Thailand": ".th",
    "East Timor": ".tl",
    "Turkey": ".tr",
    "Turkmenistan": ".tm",
    "United Arab Emirates": ".ae",
    "Uzbekistan": ".uz",
    "Vietnam": ".vn",
    "Yemen": ".ye",
    
    # ==================== EUROPE ====================
    "Albania": ".al",
    "Andorra": ".ad",
    "Austria": ".at",
    "Belarus": ".by",
    "Belgium": ".be",
    "Bosnia and Herzegovina": ".ba",
    "Bulgaria": ".bg",
    "Croatia": ".hr",
    "Czech Republic": ".cz",
    "Denmark": ".dk",
    "Estonia": ".ee",
    "Finland": ".fi",
    "France": ".fr",
    "Germany": ".de",
    "Greece": ".gr",
    "Hungary": ".hu",
    "Iceland": ".is",
    "Ireland": ".ie",
    "Italy": ".it",
    "Kosovo": ".xk",  # Unofficial
    "Latvia": ".lv",
    "Liechtenstein": ".li",
    "Lithuania": ".lt",
    "Luxembourg": ".lu",
    "Malta": ".mt",
    "Moldova": ".md",
    "Monaco": ".mc",
    "Montenegro": ".me",
    "Netherlands": ".nl",
    "North Macedonia": ".mk",
    "Norway": ".no",
    "Poland": ".pl",
    "Portugal": ".pt",
    "Romania": ".ro",
    "San Marino": ".sm",
    "Serbia": ".rs",
    "Slovakia": ".sk",
    "Slovenia": ".si",
    "Spain": ".es",
    "Sweden": ".se",
    "Switzerland": ".ch",
    "Ukraine": ".ua",
    "United Kingdom": ".uk",
    "Vatican City": ".va",
    
    # ==================== NORTH AMERICA ====================
    "Antigua and Barbuda": ".ag",
    "Bahamas": ".bs",
    "Barbados": ".bb",
    "Belize": ".bz",
    "Canada": ".ca",
    "Costa Rica": ".cr",
    "Cuba": ".cu",
    "Dominica": ".dm",
    "Dominican Republic": ".do",
    "El Salvador": ".sv",
    "Grenada": ".gd",
    "Guatemala": ".gt",
    "Haiti": ".ht",
    "Honduras": ".hn",
    "Jamaica": ".jm",
    "Mexico": ".mx",
    "Nicaragua": ".ni",
    "Panama": ".pa",
    "Saint Kitts and Nevis": ".kn",
    "Saint Lucia": ".lc",
    "Saint Vincent and the Grenadines": ".vc",
    "Trinidad and Tobago": ".tt",
    "United States": ".us",
    
    # ==================== SOUTH AMERICA ====================
    "Argentina": ".ar",
    "Bolivia": ".bo",
    "Brazil": ".br",
    "Chile": ".cl",
    "Colombia": ".co",
    "Ecuador": ".ec",
    "Guyana": ".gy",
    "Paraguay": ".py",
    "Peru": ".pe",
    "Suriname": ".sr",
    "Uruguay": ".uy",
    "Venezuela": ".ve",
    
    # ==================== AFRICA ====================
    "Algeria": ".dz",
    "Angola": ".ao",
    "Benin": ".bj",
    "Botswana": ".bw",
    "Burkina Faso": ".bf",
    "Burundi": ".bi",
    "Cameroon": ".cm",
    "Cape Verde": ".cv",
    "Central African Republic": ".cf",
    "Chad": ".td",
    "Comoros": ".km",
    "Democratic Republic of the Congo": ".cd",
    "Republic of the Congo": ".cg",
    "Djibouti": ".dj",
    "Egypt": ".eg",
    "Equatorial Guinea": ".gq",
    "Eritrea": ".er",
    "Eswatini": ".sz",
    "Ethiopia": ".et",
    "Gabon": ".ga",
    "Gambia": ".gm",
    "Ghana": ".gh",
    "Guinea": ".gn",
    "Guinea-Bissau": ".gw",
    "Ivory Coast": ".ci",
    "Kenya": ".ke",
    "Lesotho": ".ls",
    "Liberia": ".lr",
    "Libya": ".ly",
    "Madagascar": ".mg",
    "Malawi": ".mw",
    "Mali": ".ml",
    "Mauritania": ".mr",
    "Mauritius": ".mu",
    "Morocco": ".ma",
    "Mozambique": ".mz",
    "Namibia": ".na",
    "Niger": ".ne",
    "Nigeria": ".ng",
    "Rwanda": ".rw",
    "Sao Tome and Principe": ".st",
    "Senegal": ".sn",
    "Seychelles": ".sc",
    "Sierra Leone": ".sl",
    "Somalia": ".so",
    "South Africa": ".za",
    "South Sudan": ".ss",
    "Sudan": ".sd",
    "Tanzania": ".tz",
    "Togo": ".tg",
    "Tunisia": ".tn",
    "Uganda": ".ug",
    "Zambia": ".zm",
    "Zimbabwe": ".zw",
    
    # ==================== OCEANIA ====================
    "Australia": ".au",
    "Fiji": ".fj",
    "Kiribati": ".ki",
    "Marshall Islands": ".mh",
    "Micronesia": ".fm",
    "Nauru": ".nr",
    "New Zealand": ".nz",
    "Palau": ".pw",
    "Papua New Guinea": ".pg",
    "Samoa": ".ws",
    "Solomon Islands": ".sb",
    "Tonga": ".to",
    "Tuvalu": ".tv",
    "Vanuatu": ".vu",
    
    # ==================== TERRITORIES ====================
    "American Samoa": ".as",
    "Anguilla": ".ai",
    "Aruba": ".aw",
    "Bermuda": ".bm",
    "British Virgin Islands": ".vg",
    "Cayman Islands": ".ky",
    "Cook Islands": ".ck",
    "Falkland Islands": ".fk",
    "Faroe Islands": ".fo",
    "French Guiana": ".gf",
    "French Polynesia": ".pf",
    "Gibraltar": ".gi",
    "Greenland": ".gl",
    "Guadeloupe": ".gp",
    "Guam": ".gu",
    "Martinique": ".mq",
    "Montserrat": ".ms",
    "New Caledonia": ".nc",
    "Niue": ".nu",
    "Northern Mariana Islands": ".mp",
    "Puerto Rico": ".pr",
    "Reunion": ".re",
    "Saint Helena": ".sh",
    "Sint Maarten": ".sx",
    "Turks and Caicos Islands": ".tc",
    "US Virgin Islands": ".vi",
    "Wallis and Futuna": ".wf",
}
