# allykit/__init__.py
# allykit <<< ¶¶

"""
allykit - Ultimate Toolkit for Python Developers
===============================================
Dear friend, after installing this module, please run this command in your terminal so that you can use allykit correctly.
>>>  pip install selenium beautifulsoup4 requests tenacity deepdiff 
"""

# ==================== Automobile_kit ====================
from .Automobile_kit.Automobile.Cmd import cmd
from .Automobile_kit.Automobile.powerShell import PowerShell
from .Automobile_kit.New_automobile.python import Pip , Python
from .Automobile_kit.Automobile.hybrid import hash_password
from .Automobile_kit.New_automobile.file import File
from .Automobile_kit.New_automobile.git import Git
from allykit.Automobile_kit.ProcessManager import ( 
    ProcessManager,
    kill_process,
    kill_chrome, 
    kill_firefox, 
    kill_edge, 
    kill_all_browsers, 
    get_process_info,
    is_process_running,
    count_processes,
    suspend_process,
    resume_process,
    get_process_pids
)


# ==================== Tools_kit ====================
from .Tools_kit.WorkFileJson import WorkFileJson


from .Tools_kit.file_tools import (
    remove_file,
    remove_files,
    is_dir,
    write_file,
    dump_file,
    load_file,
    read_file,
    get_permission,
    change_permission,
    get_stat_info,
    datetime_file,
    type_file,
    information_files,
    information_files_dict,
)

from .Tools_kit.string_tools import (
    choice_string,
    choice_string_yield,
    str_choice_string,
    list_choice_string,
    truncate,
    format_thousands
)

# ==================== Security ====================
from .Security_kit import  (
    # Password
    choice_string , choice_string_yield , 
    str_choice_string ,list_choice_string , 
    generate_password , generate_strong_password,
    generate_password_with_prefix_suffix, 
    wrap_password_with_time, generate_timed_password, Time_Password, Review_Password,
    # file 
    hash_file, dict_files_in_directory , find_file , hash_file, save_dict_and_expected , dict_files_in_directory_bool,
    verify_snapshot , create_snapshot,
    # hash
    smart_hash_detector , detect_hash_algorithm, hash_file , hash_password, verify_password,
    hash_with_salt , generate_salt , find_matching_hashes , compare_hash , double_hash, 
    hash_url, calculate_file_hashes  
)


# ==================== Web ====================
from .web_kit import fix_url
from .web_kit.CChrome import chrome, get_headless_driver , browser_context, wait_for_element
from .web_kit.Communications import get_rate_limit_info, fetch_url, is_link_alive, validate_links, execute_request
from .web_kit.Elastic_bands import Monitoring, DiskCache
from .web_kit.Get_Code import soup_url, javascript, javascript_driver , javascript_pro
from .web_kit.WebAutomation import WebAutomation, By
from .web_kit.Working_with_code import SoupToDict, extract_structured_data , extract_all_links,extract_images,extract_text_from_tags,save_link,save_links
from .web_kit.Cookie import Cookie
from .web_kit.scroll_manager import (
    py_scroll,
    window_scrollTo,
    window_scrollTo_bottom,
    window_scrollTo_top,
    window_scrollTo_right,
    scroll_smooth_to,
    scroll_to_element,
    get_scroll_info,
    scroll_to_percentage,
    scroll_until_element_visible,
    scroll_infinite_loader,
    scroll_animated_spiral,
    scroll_to_text,
    ScrollManager
)


# ==================== Language & Geography ====================
from .data_kit.country import (
    CALLING_CODES,
    COUNTRY_TO_CODE,
    ISO_ALPHA2,
    COUNTRY_CONTINENT,
    COUNTRY_TLD,
    COUNTRY_TLD
)
from .data_kit.IRAN import (
    PERSIAN_CHARSET , 
    PERSIAN_LETTERS,
    PERSIAN_DIGITS,
    PUNCTUATION_UNICODE,
    PERSIAN_DIACRITICS
    )
from .data_kit.Language import (
    # Whitespace
    WHITESPACE,
    WHITESPACE_STANDARD,
    WHITESPACE_LIST,
    WHITESPACE_EXTRA,
    WHITESPACE_ALL,
    
    # Punctuation
    PUNCTUATION_ASCII,
    PUNCTUATION_UNICODE,
    PUNCTUATION_EXTRA,
    PUNCTUATION,
    PUNCTUATION_LIST,
    
    # Numeric Systems
    BINARY_DIGITS,
    OCTAL_DIGITS,
    DECIMAL_DIGITS,
    HEX_DIGITS,
    PERSIAN_DIGITS,
    PERSIAN_DIGITS_MAP,
    EASTERN_ARABIC_DIGITS,
    DEVANAGARI_DIGITS,
    BENGALI_DIGITS,
    THAI_DIGITS,
    TAMIL_DIGITS,
    TELUGU_DIGITS,
    KANNADA_DIGITS,
    MALAYALAM_DIGITS,
    GURMUKHI_DIGITS,
    GUJARATI_DIGITS,
    ORIYA_DIGITS,
    TIBETAN_DIGITS,
    MYANMAR_DIGITS,
    KHMER_DIGITS,
    LAO_DIGITS,
    MONGOLIAN_DIGITS,
    JAVANESE_DIGITS,
    BALINESE_DIGITS,
    SUNDANESE_DIGITS,
    LEPCHA_DIGITS,
    OL_CHIKI_DIGITS,
    SAURASHTRA_DIGITS,
    WARANG_CITI_DIGITS,
    MAHAJANI_DIGITS,
    MODI_DIGITS,
    NANDINAGARI_DIGITS,
    TAKRI_DIGITS,
    DOGRA_DIGITS,
    CIRCLED_NUMBERS,
    PARENTHESIZED_NUMBERS,
    ROMAN_NUMERALS_UPPER,
    ROMAN_NUMERALS_LOWER,
    CHINESE_NUMBERS,
    ALL_DIGITS,
    
    # Latin-based Alphabets
    ASCII_LOWERCASE,
    ASCII_UPPERCASE,
    ASCII_LETTERS,
    GERMAN_LOWERCASE,
    GERMAN_UPPERCASE,
    FRENCH_LOWERCASE,
    FRENCH_UPPERCASE,
    SPANISH_LOWERCASE,
    SPANISH_UPPERCASE,
    ITALIAN_LOWERCASE,
    ITALIAN_UPPERCASE,
    PORTUGUESE_LOWERCASE,
    PORTUGUESE_UPPERCASE,
    DUTCH_LOWERCASE,
    DUTCH_UPPERCASE,
    ROMANIAN_LOWERCASE,
    ROMANIAN_UPPERCASE,
    POLISH_LOWERCASE,
    POLISH_UPPERCASE,
    CZECH_LOWERCASE,
    CZECH_UPPERCASE,
    SLOVAK_LOWERCASE,
    SLOVAK_UPPERCASE,
    HUNGARIAN_LOWERCASE,
    HUNGARIAN_UPPERCASE,
    CROATIAN_LOWERCASE,
    CROATIAN_UPPERCASE,
    SLOVENE_LOWERCASE,
    SLOVENE_UPPERCASE,
    LITHUANIAN_LOWERCASE,
    LITHUANIAN_UPPERCASE,
    LATVIAN_LOWERCASE,
    LATVIAN_UPPERCASE,
    ESTONIAN_LOWERCASE,
    ESTONIAN_UPPERCASE,
    FINNISH_LOWERCASE,
    FINNISH_UPPERCASE,
    SWEDISH_LOWERCASE,
    SWEDISH_UPPERCASE,
    NORWEGIAN_LOWERCASE,
    NORWEGIAN_UPPERCASE,
    DANISH_LOWERCASE,
    DANISH_UPPERCASE,
    ICELANDIC_LOWERCASE,
    ICELANDIC_UPPERCASE,
    FAROESE_LOWERCASE,
    FAROESE_UPPERCASE,
    TURKISH_LOWERCASE,
    TURKISH_UPPERCASE,
    AZERBAIJANI_LOWERCASE,
    AZERBAIJANI_UPPERCASE,
    VIETNAMESE_LOWERCASE,
    VIETNAMESE_UPPERCASE,
    CATALAN_LOWERCASE,
    CATALAN_UPPERCASE,
    WELSH_LOWERCASE,
    WELSH_UPPERCASE,
    MALTESE_LOWERCASE,
    MALTESE_UPPERCASE,
    IRISH_LOWERCASE,
    IRISH_UPPERCASE,
    SCOTS_GAELIC_LOWERCASE,
    SCOTS_GAELIC_UPPERCASE,
    BASQUE_LOWERCASE,
    BASQUE_UPPERCASE,
    GALICIAN_LOWERCASE,
    GALICIAN_UPPERCASE,
    ESPERANTO_LOWERCASE,
    ESPERANTO_UPPERCASE,
    ALBANIAN_LOWERCASE,
    ALBANIAN_UPPERCASE,
    BOSNIAN_LOWERCASE,
    BOSNIAN_UPPERCASE,
    SERBIAN_LATIN_LOWERCASE,
    SERBIAN_LATIN_UPPERCASE,
    MONTENEGRIN_LATIN_LOWERCASE,
    MONTENEGRIN_LATIN_UPPERCASE,
    MACEDONIAN_LATIN_LOWERCASE,
    MACEDONIAN_LATIN_UPPERCASE,
    TURKMEN_LOWERCASE,
    TURKMEN_UPPERCASE,
    CRIMEAN_TATAR_LOWERCASE,
    CRIMEAN_TATAR_UPPERCASE,
    BRETON_LOWERCASE,
    BRETON_UPPERCASE,
    FRIULIAN_LOWERCASE,
    FRIULIAN_UPPERCASE,
    ROMSH_LOWERCASE,
    ROMSH_UPPERCASE,
    LUXEMBOURGISH_LOWERCASE,
    LUXEMBOURGISH_UPPERCASE,
    CORSICAN_LOWERCASE,
    CORSICAN_UPPERCASE,
    SARDINIAN_LOWERCASE,
    SARDINIAN_UPPERCASE,
    SICILIAN_LOWERCASE,
    SICILIAN_UPPERCASE,
    NEAPOLITAN_LOWERCASE,
    NEAPOLITAN_UPPERCASE,
    ASTURIAN_LOWERCASE,
    ASTURIAN_UPPERCASE,
    ARAGONESE_LOWERCASE,
    ARAGONESE_UPPERCASE,
    OCCITAN_LOWERCASE,
    OCCITAN_UPPERCASE,
    WALLOON_LOWERCASE,
    WALLOON_UPPERCASE,
    LADIN_LOWERCASE,
    LADIN_UPPERCASE,
    MIRANDESE_LOWERCASE,
    MIRANDESE_UPPERCASE,
    
    # Cyrillic Alphabets
    RUSSIAN_LOWERCASE,
    RUSSIAN_UPPERCASE,
    UKRAINIAN_LOWERCASE,
    UKRAINIAN_UPPERCASE,
    BULGARIAN_LOWERCASE,
    BULGARIAN_UPPERCASE,
    SERBIAN_CYRILLIC_LOWERCASE,
    SERBIAN_CYRILLIC_UPPERCASE,
    MACEDONIAN_CYRILLIC_LOWERCASE,
    MACEDONIAN_CYRILLIC_UPPERCASE,
    BELARUSIAN_LOWERCASE,
    BELARUSIAN_UPPERCASE,
    MONGOLIAN_CYRILLIC_LOWERCASE,
    MONGOLIAN_CYRILLIC_UPPERCASE,
    KAZAKH_CYRILLIC_LOWERCASE,
    KAZAKH_CYRILLIC_UPPERCASE,
    KYRGYZ_CYRILLIC_LOWERCASE,
    KYRGYZ_CYRILLIC_UPPERCASE,
    TAJIK_CYRILLIC_LOWERCASE,
    TAJIK_CYRILLIC_UPPERCASE,
    TATAR_CYRILLIC_LOWERCASE,
    TATAR_CYRILLIC_UPPERCASE,
    BASHKIR_CYRILLIC_LOWERCASE,
    BASHKIR_CYRILLIC_UPPERCASE,
    CHUVASH_CYRILLIC_LOWERCASE,
    CHUVASH_CYRILLIC_UPPERCASE,
    OSSETIAN_CYRILLIC_LOWERCASE,
    OSSETIAN_CYRILLIC_UPPERCASE,
    MARI_CYRILLIC_LOWERCASE,
    MARI_CYRILLIC_UPPERCASE,
    UDMURT_CYRILLIC_LOWERCASE,
    UDMURT_CYRILLIC_UPPERCASE,
    
    # Arabic-based Scripts
    ARABIC_LETTERS,
    ARABIC_LETTERS_LIST,
    ARABIC_ALL_FORMS,
    PERSIAN_LETTERS,
    PERSIAN_LETTERS_LIST,
    PERSIAN_FULL,
    URDU_LETTERS,
    URDU_LETTERS_LIST,
    PASHTO_LETTERS,
    PASHTO_LETTERS_LIST,
    KURDISH_ARABIC,
    KURDISH_ARABIC_LIST,
    SINDHI_LETTERS,
    SINDHI_LETTERS_LIST,
    UYGHUR_ARABIC,
    UYGHUR_ARABIC_LIST,
    JAWI_LETTERS,
    JAWI_LETTERS_LIST,
    BALOCHI_ARABIC,
    BALOCHI_ARABIC_LIST,
    KASHMIRI_ARABIC,
    KASHMIRI_ARABIC_LIST,
    
    # South Asian Scripts
    DEVANAGARI_VOWELS,
    DEVANAGARI_CONSONANTS,
    DEVANAGARI_LETTERS,
    DEVANAGARI_LETTERS_LIST,
    BENGALI_VOWELS,
    BENGALI_CONSONANTS,
    BENGALI_LETTERS,
    BENGALI_LETTERS_LIST,
    GURMUKHI_VOWELS,
    GURMUKHI_CONSONANTS,
    GURMUKHI_LETTERS,
    GUJARATI_VOWELS,
    GUJARATI_CONSONANTS,
    GUJARATI_LETTERS,
    ODIA_VOWELS,
    ODIA_CONSONANTS,
    ODIA_LETTERS,
    TAMIL_VOWELS,
    TAMIL_CONSONANTS,
    TAMIL_LETTERS,
    TELUGU_VOWELS,
    TELUGU_CONSONANTS,
    TELUGU_LETTERS,
    KANNADA_VOWELS,
    KANNADA_CONSONANTS,
    KANNADA_LETTERS,
    MALAYALAM_VOWELS,
    MALAYALAM_CONSONANTS,
    MALAYALAM_LETTERS,
    SINHALA_VOWELS,
    SINHALA_CONSONANTS,
    SINHALA_LETTERS,
    MARATHI_EXTRA,
    
    # Southeast Asian Scripts
    THAI_CONSONANTS,
    THAI_VOWELS,
    THAI_TONES,
    THAI_LETTERS,
    LAO_CONSONANTS,
    LAO_VOWELS,
    LAO_LETTERS,
    KHMER_CONSONANTS,
    KHMER_VOWELS,
    KHMER_LETTERS,
    MYANMAR_CONSONANTS,
    MYANMAR_VOWELS,
    MYANMAR_LETTERS,
    JAVANESE_LETTERS,
    JAVANESE_VOWELS,
    BALINESE_LETTERS,
    BALINESE_VOWELS,
    
    # East Asian Scripts
    CHINESE_COMMON,
    CHINESE_LETTERS_LIST,
    HIRAGANA,
    KATAKANA,
    JAPANESE_LETTERS,
    HANGUL_INITIAL,
    HANGUL_MEDIAL,
    HANGUL_FINAL,
    HANGUL_SYLLABLES,
    HANGUL_LETTERS,
    
    # Other Scripts
    GREEK_LOWERCASE,
    GREEK_UPPERCASE,
    GREEK_LETTERS,
    HEBREW_LETTERS,
    HEBREW_FULL,
    ARMENIAN_LOWERCASE,
    ARMENIAN_UPPERCASE,
    ARMENIAN_LETTERS,
    GEORGIAN_MKHEDRULI,
    GEORGIAN_ASOMTAVRULI,
    GEORGIAN_LETTERS,
    AMHARIC_LETTERS,
    TIBETAN_CONSONANTS,
    TIBETAN_VOWELS,
    TIBETAN_LETTERS,
    SYRIAC_LETTERS,
    SYRIAC_LETTERS_LIST,
    THAANA_LETTERS,
    CHEROKEE_LETTERS,
    IPA_CONSONANTS,
    IPA_VOWELS,
    PHOENICIAN,
    CUNEIFORM_SAMPLE,
    
    # Symbols and Special Characters
    CURRENCY_SYMBOLS,
    MATH_SYMBOLS,
    ARROWS,
    MUSIC_SYMBOLS,
    CHESS_SYMBOLS,
    CARDS_SYMBOLS,
    ZODIAC_SYMBOLS,
    ASTRONOMY_SYMBOLS,
    WEATHER_SYMBOLS,
    FRACTIONS,
    BOX_DRAWING,
    COMMON_EMOJIS,
    EMOJI_FLAGS,
    PERSIAN_HARAKAT,
    PERSIAN_PUNCTUATION,
    ARABIC_DIACRITICS,
    
    # Comprehensive Collections
    ALL_LATIN_LOWERCASE,
    ALL_LATIN_UPPERCASE,
    ALL_LATIN_LETTERS,
    ALL_CYRILLIC_LOWERCASE,
    ALL_CYRILLIC_UPPERCASE,
    ALL_CYRILLIC,
    ALL_ARABIC_SCRIPTS,
    ALL_SOUTH_ASIAN,
    ALL_CHARACTERS,
    
    # Printable Character Sets
    PRINTABLE_ASCII,
    PRINTABLE_LATIN,
    PRINTABLE_CYRILLIC,
    PRINTABLE_ARABIC,
    PRINTABLE_SOUTH_ASIAN,
    PRINTABLE_EAST_ASIAN,
    PRINTABLE_GREEK,
    PRINTABLE_HEBREW,
    PRINTABLE_ARMENIAN,
    PRINTABLE_GEORGIAN,
    PRINTABLE_THAI,
    PRINTABLE_LAO,
    PRINTABLE_KHMER,
    PRINTABLE_MYANMAR,
    PRINTABLE_TIBETAN,
    PRINTABLE_MONGOLIAN,
    PRINTABLE_CHEROKEE,
    PRINTABLE_ETHIOPIC,
    
    # Language-Specific Printable Sets
    PRINTABLE_GERMAN,
    PRINTABLE_FRENCH,
    PRINTABLE_SPANISH,
    PRINTABLE_ITALIAN,
    PRINTABLE_PORTUGUESE,
    PRINTABLE_DUTCH,
    PRINTABLE_POLISH,
    PRINTABLE_CZECH,
    PRINTABLE_TURKISH,
    PRINTABLE_VIETNAMESE,
    PRINTABLE_RUSSIAN,
    PRINTABLE_UKRAINIAN,
    PRINTABLE_ARABIC,
    PRINTABLE_PERSIAN,
    PRINTABLE_URDU,
    PRINTABLE_HINDI,
    PRINTABLE_BENGALI,
    PRINTABLE_PUNJABI,
    PRINTABLE_GUJARATI,
    PRINTABLE_TAMIL,
    PRINTABLE_TELUGU,
    PRINTABLE_KANNADA,
    PRINTABLE_MALAYALAM,
    PRINTABLE_JAPANESE,
    PRINTABLE_CHINESE,
    PRINTABLE_KOREAN,
    
    # Functional Character Sets
    URL_SAFE,
    BASE64_CHARS,
    HEX_CHARS,
    IDENTIFIER_CHARS,
    PASSWORD_SPECIAL,
    EMAIL_LOCAL_CHARS,
    DOMAIN_CHARS,
    
    # Language Group Sets
    GERMANIC_LANGUAGES_CHARS,
    ROMANCE_LANGUAGES_CHARS,
    SLAVIC_LATIN_CHARS,
    SLAVIC_CYRILLIC_CHARS,
    TURKIC_LANGUAGES_CHARS,
    
    # Text Classification Sets
    BIDI_CHARS,
    RTL_CHARS,
    LTR_CHARS,
    TTB_CHARS,
    
    # Usage Categories
    UI_SAFE_CHARS,
    FILENAME_SAFE_CHARS,
    XML_SAFE_CHARS,
    HTML_ESCAPE_CHARS,
    XML_ESCAPE_CHARS,
    JSON_ESCAPE_CHARS,
    PYTHON_ESCAPE_CHARS,
    
    # Metrics and Statistics
    UNIQUE_ALL_CHARACTERS,
    TOTAL_UNIQUE_CHARS,
    LATIN_LANGUAGES_COUNT,
    CYRILLIC_LANGUAGES_COUNT,
    ARABIC_LANGUAGES_COUNT,
    SOUTH_ASIAN_LANGUAGES_COUNT,
    TOTAL_LANGUAGES_COVERED,
    
    # Character Property Mappings
    CHAR_CATEGORY_MAP,
    ASCII_LETTER_CHARS,
    ASCII_DIGIT_CHARS,
    ASCII_PUNCT_CHARS,
    ASCII_WHITESPACE_CHARS,
    ASCII_CONTROL_CHARS,
    ASCII_PRINTABLE_CHARS,
    
    # String Validation Patterns
    ALPHA_CHARS,
    ALPHANUMERIC_CHARS,
    ALPHANUMERIC_EXTENDED,
    NUMERIC_CHARS,
    INTEGER_CHARS,
    FLOAT_CHARS,
    HEX_NUMERIC_CHARS,
    OCTAL_NUMERIC_CHARS,
    BINARY_NUMERIC_CHARS,
    
    # Special Character Subsets
    INVISIBLE_CHARS,
    HOMOGLYPH_LATIN_A,
    HOMOGLYPH_LATIN_B,
    HOMOGLYPH_LATIN_E,
    HOMOGLYPH_LATIN_H,
    HOMOGLYPH_LATIN_I,
    HOMOGLYPH_LATIN_K,
    HOMOGLYPH_LATIN_M,
    HOMOGLYPH_LATIN_N,
    HOMOGLYPH_LATIN_O,
    HOMOGLYPH_LATIN_P,
    HOMOGLYPH_LATIN_T,
    HOMOGLYPH_LATIN_X,
    HOMOGLYPH_LATIN_Y,
    ZERO_WIDTH_CHARS,
    DIRECTION_CHARS,
    
    # Database and Storage
    SQL_IDENTIFIER_CHARS,
    BASE32_CHARS,
    CROCKFORD_BASE32,
    
    # Display and Rendering
    DESCENDER_CHARS,
    ASCENDER_CHARS,
    MONOSPACE_DIGITS,
    VARIABLE_WIDTH_CHARS,
    FULLWIDTH_CHARS,
    HALFWIDTH_CHARS,
    
    # Historical and Rare Scripts
    RUNIC_CHARS,
    OGHAM_CHARS,
    GOTHIC_CHARS,
    DESERET_CHARS,
    
    # Export Configurations
    ASCII_COMPATIBLE,
    LATIN1_COMPATIBLE,
    UTF8_COMPATIBLE,
    UTF16_COMPATIBLE,
    BOM_UTF8,
    BOM_UTF16_LE,
    BOM_UTF16_BE,
    BOM_UTF32_LE,
    BOM_UTF32_BE,
)

# ==================== Version & Metadata ====================
__version__ = "1.4"
__author__ = None
__license__ = "MIT"
__status__ = "Alpha"